version: "3.5"
services:
  postgres:
     image: postgres:12-alpine
     container_name: postgres
     ports:
       - "5432"
     networks:
       - otlm
     volumes:
       - /etc/localtime:/etc/localtime:ro
       - postgres_data:/var/lib/postgresql/data
     environment:
       POSTGRES_USER: postgresComland
       POSTGRES_PASSWORD: postComland15/
       POSTGRES_DB: otlm

  otlm_pact_broker:
     image: dius/pact-broker
     container_name: otlm_pact_broker
     ports:
       - "8888:80"
     networks:
       - otlm
     depends_on:
       - postgres
       - nginx
     volumes:
       - /etc/localtime:/etc/localtime:ro
     environment:
       PACT_BROKER_DATABASE_USERNAME: postgresComland
       PACT_BROKER_DATABASE_PASSWORD: postComland15/
       PACT_BROKER_DATABASE_HOST: postgres
       PACT_BROKER_DATABASE_NAME: otlm
       PACT_BROKER_BASIC_AUTH_USERNAME: pact
       PACT_BROKER_BASIC_AUTH_PASSWORD: pactComland15
  nginx:
    image: nginx:alpine
    container_name: nginx_otlm
    restart: always
    networks:
      - otlm
    volumes:
      - ./ssl/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl
    ports:
      - "8443:443"
volumes:
  postgres_data:
    name: postgres_data
networks:
  otlm:
    name: otlm