export enum MeterUnitsTypeEnum {
  connect = 'connect',
  disconnect = 'disconnect',
  breakerStatus = 'breakerStatus',
  touConfig = 'touConfig',
  activateUpgrade = 'activateUpgrade',
  delete = 'delete',
  clearFF = 'clearFF',
  ciiActivate = 'ciiActivate',
  ciiDeactivate = 'ciiDeactivate',
  ciiState = 'ciiState',
  relaysState = 'relaysState',
  relaysConnect = 'relaysConnect',
  relaysDisconnect = 'relaysDisconnect',
  relaysMode = 'relaysMode',
  clearAlarms = 'clearAlarms',
  readThresholdsLimiter = 'readThresholdsLimiter',
  readThresholdsMonitor = 'readThresholdsMonitor',
  syncTime = 'syncTime',
  readMeter = 'readMeter'
}
